# Generated by Django 6.0.2 on 2026-03-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='condition_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='damage_notes',
            field=models.TextField(blank=True, help_text='Customer notes on existing damage'),
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='garage',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Vehicle Owner'), ('mechanic', 'Mechanic'), ('manager', 'Garage Manager'), ('admin', 'Admin')], default='owner', max_length=10),
        ),
    ]
