# Generated by Django 6.0.3 on 2026-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehicle_condition_submitted_vehicle_damage_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager_created',
            field=models.BooleanField(default=False),
        ),
    ]
