# Generated by Django 6.0.3 on 2026-03-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_manager_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingManagerProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Manager Request',
                'verbose_name_plural': '🟠 Manager Requests (Pending Approval)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
    ]
