# Generated by Django 6.0.2 on 2026-03-28 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_garage_landmark_garage_maps_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='GarageTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund')], default='credit', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.booking')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.garage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
