# Generated by Django 6.0.2 on 2026-03-28 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_garage_wallet_balance_garagetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='manager_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='manager_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='wallet_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='wallet_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted by Mechanic'), ('on_way', 'On the Way'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('quality_check', 'Quality Check'), ('completed', 'Completed'), ('verified', 'Manager Verified'), ('issue_reported', 'Issue Reported')], default='assigned', max_length=20),
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.job')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
