# Generated by Django 6.0.2 on 2026-03-28 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bookingmessage_jobdecline'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_method',
            field=models.CharField(default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='labour_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='parts_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='garage',
            name='advance_fee',
            field=models.DecimalField(decimal_places=2, default=600, help_text='Booking confirmation advance fee charged to customer (₹)', max_digits=8),
        ),
        migrations.AddField(
            model_name='jobpart',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpart',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpart',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='GarageCustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(default='🔧', max_length=8)),
                ('category', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('both', 'Car & Bike')], default='both', max_length=5)),
                ('price_basic', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_standard', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_premium', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_services', to='core.garage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MechanicEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('earning_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credited_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.garage')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='core.job')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-credited_at'],
            },
        ),
        migrations.CreateModel(
            name='GarageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_offered', models.BooleanField(default=True)),
                ('price_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_services', to='core.garage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_offerings', to='core.service')),
            ],
            options={
                'ordering': ['service__order', 'service__name'],
                'unique_together': {('garage', 'service')},
            },
        ),
    ]
