# Generated by Django 6.0.2 on 2026-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_advance_amount_booking_advance_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
