# Generated by Django 6.0.2 on 2026-04-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_jobpart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(default='advance', max_length=20),
        ),
    ]
